spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Ly20020622.123
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  template:
    cache: false
  jpa:
    database: mysql
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: 500
          batch_versioned_data: true
  profiles:
    active: import

  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
  mvc:
    static-path-pattern: /**